### ISSUE TITLE
Add Pin-Priority support

### ISSUE THREAD

**Issue by sfuerte** [jnv/ansible-role-debian-backports#10]
By default `backports` have lower priority but possible to increase it via APT preferences. 
Any possibility to add support for it?

**Comment by jnv** [comment]
Hi @sfuerte, AFAIK this would require messing with APT preferences which cannot be neatly managed through some Ansible module. Personally I find this feature outside of the scope of this role and I don't want to take on the maintenace. Setting the `default_release` parameter during package(s) installation is a preferred option.

However, if you would like to implement this feature either in a fork or separate role, let me know and I will mention it in the README.

**Comment by sfuerte** [comment]
Not quite sure why it cannot be neatly managed or why it'll be messing with preferences. Even the official documentation has no problem with it:
https://wiki.debian.org/AptConfiguration#Always_prefer_packages_from_a_repository

Here is a PR as example: 
- defaults to system value of 100 and no changes
- changing the value will create `/etc/apt/preferences.d/001_backports` with corresponding settings
- reverting back to 100, will delete the file and reset to system default

https://github.com/jnv/ansible-role-debian-backports/pull/11
