### ISSUE TITLE
Override of `backports_uri` fails

### ISSUE THREAD

**Issue by nevart** [jnv/ansible-role-debian-backports#14]
Thanks for handling of #12, I think the chosen path makes sense.

While trying to override `backports_uri`, to opt-in to use HTTPS on a Debian system, via `group_vars`, I ran into a problem: the override doesn't have any effect.

After looking again into [the docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence), the precedence of `include_vars`, as used in [the code](https://github.com/jnv/ansible-role-debian-backports/blob/master/tasks/main.yml#L3) is higher than most of the other mechanisms to provide variables, including `group_vars`.

Any idea how to deal with this? Is there an alternative we could make use of in this role, to load OS-specific variables, while still keeping the ability to override them?

**Comment by jnv** [comment]
Hi @nevart, thanks for reporting the issue. I think the cleanest path would be to introduce a new internal variable to provide default / fallback value loaded through `include_vars`. This variable would be used only if the `backports_uri` is not set.

I am currently on a vacation, but I can take a look at it in a week or two.

**Comment by nevart** [comment]
Thanks for your quick feedback, if you could have a look, this would be very much appreciated. :)

But: no rush please; enjoy your vacation!

**Comment by nevart** [comment]
This [post](https://stackoverflow.com/a/58078985/5071547) deals with the question how to achieve this and links to a role making use of `internal` / `pseudo` variables.
