### ISSUE TITLE
https://archive.ubuntu.com/ubuntu is not available

### ISSUE THREAD

**Issue by eudora-fabia** [jnv/ansible-role-debian-backports#20]
For Ubuntu Bionic(18.04) Use `http://archive.ubuntu.com/ubuntu`

**Comment by xshadow** [comment]
Please provide more information :)

**Comment by jnv** [comment]
You are right, the server doesn't respond to HTTPS port anymore. This is just a simple modification of default URL, I'll make it on Monday,though PR is welcome.
