### ISSUE TITLE
Fails on debian 8

### ISSUE THREAD

**Issue by t2d** [jnv/ansible-role-debian-backports#4]
Thank you for providing this nice role. Sadly, it fails at the moment when using Debian 8. This wasn't the case in the past. See this example when using your role as dependency
https://travis-ci.org/systemli/ansible-role-needrestart/jobs/489183521

**Comment by rlsit** [comment]
same issue on another ansible playbook using the backporst role:
https://travis-ci.org/rlsit/ansible-role-nextcloud/builds/523927481
Oldstable has no backports anymore
http://cdn-fastly.deb.debian.org/debian/dists/

From https://backports.debian.org/

> Deprecation of LTS support for backports
> 
> We started supporting backports as long as there is LTS support as an experiment. Unfortunately it didn't worked, most maintainers didn't wanted to support oldoldstable-backports (squeeze) for the lifetime of LTS. So things started to rot in squeeze and most packages didn't received updates. After long discussions we decided to deprecate LTS support for backports. From now on squeeze-backports(-sloppy) is closed and will not receive any updates. Expect it to get removed from the mirrors and moved to archive in the near future.

**Comment by t2d** [comment]
@rlsit thank you for clearing this up. So I'm going to close this issue again and pull support for Debian Oldstable

**Comment by jnv** [comment]
Thanks for clearing this up. We can add note about the depreciation to the role's README if you think it is still useful. PR welcome.
