### ISSUE TITLE
v0.4.1 missing on ansible-galaxy 

### ISSUE THREAD

**Issue by xshadow** [jnv/ansible-role-debian-backports#8]
The latest version/tag of this role is missing on ansible galaxy

Please let ansible galaxy rescan the github repository, then the version should be listed and used. 

Thank you!

**Comment by jnv** [comment]
Thanks for the heads up! I was under impression Galaxy is supposed to pick up updates automatically. I will check it out tomorrow.

**Comment by jnv** [comment]
The package should be updated, thanks for the heads up again!

Apparently Galaxy supports only webhooks from Travis and they're not interested in fixing GitHub webhooks support: https://github.com/ansible/galaxy/issues/1379
I have added a dummy Travis config just to trigger Galaxy import, hopefully it will suffice.
